kafka:
  bootstrap_servers: kafka:9092
  topics:
    input: user-login
    processed: processed-logins
    error: error-logins
    analytics: login-analytics
    insights: login-insights
    ippatterns: login-ip-patterns
  consumer:
    group_id: login-processor-group
    auto_offset_reset: earliest

# set how long between each message being produced (in seconds)
analytics_interval:
  metrics: 30
  insights: 120
  ippatterns: 300


logging:
  level: INFO